# Generated by Django 5.2.3 on 2025-06-28 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.IntegerField(max_length=20, unique=True)),
                ('create_date', models.DateField(max_length=20)),
                ('created_by', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_contact', models.IntegerField(max_length=20)),
                ('stu_aadharno', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.aadhar', to_field='aadhar')),
            ],
        ),
    ]
